timeout: 60 # in seconds
port: 8080
namespace: "default"
resources:
  - pods
  - deployments
  - services
  - cronjobs
  - configmaps
  - secrets
  - serviceaccounts
  - statefulsets
  - hpas
  - ingresses
  - pvcs
